Documents/UCSB_classes/papersphere-master/papersphere/config/routes.rb
Papersphere::Application.routes.draw do
  
  resources :reading_list_shares

  get 'remote_library/search'
  post 'remote_library/search'

  resources :group_members

  resources :reading_list_papers, :except => [ :edit, :update ]
  match '/remove_paper_from_list' => 'reading_list_papers#remove_paper_from_list', :as => 'remove_paper_from_list'

  resources :ratings, :only => [ :create, :update ]
  resources :comments, :only => [ :create ]
  get '/comments' => 'comments#load_more_comments', :as => 'load_comments'

  resources :groups, :except => [ :new, :edit ]

  resources :papers

  resources :reading_lists, :except => [ :new, :edit ]

  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  root to: 'reading_lists#index'

end

Documents/UCSB_classes/papersphere-master/papersphere/app/models/paper.rb
class Paper < ActiveRecord::Base
  has_many :reading_list_papers, :dependent => :destroy
  has_many :reading_lists, :through => :reading_list_papers
  attr_accessible :author, :publication, :title, :url, :year, :paper_code

  validates :title, :author, :year, :publication, :paper_code, :presence => true
  
  def average_rating
    all_ratings = []
    ReadingListPaper.includes(:ratings).where(:paper_id => id).all.each do |rlp|
      rlp.ratings.each do |r|
        all_ratings << r
      end
    end
    return nil if all_ratings.empty?
    
    value = 0
    all_ratings.each do |rating|
      value += rating.value
    end
    total = all_ratings.size
    (value.to_f / total.to_f).round 3
  end
  
end

Documents/UCSB_classes/papersphere-master/papersphere/app/controllers/papers_controller.rb
class PapersController < ApplicationController
  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @papers }
    end
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
    @paper = Paper.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @paper }
    end
  end

  # GET /papers/new
  # GET /papers/new.json
  def new
    @paper = Paper.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @paper }
    end
  end

  # GET /papers/1/edit
  def edit
    @paper = Paper.find(params[:id])
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(params[:paper])

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render json: @paper, status: :created, location: @paper }
      else
        format.html { render action: "new" }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /papers/1
  # PUT /papers/1.json
  def update
    @paper = Paper.find(params[:id])

    respond_to do |format|
      if @paper.update_attributes(params[:paper])
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper = Paper.find(params[:id])
    @paper.destroy

    respond_to do |format|
      format.html { redirect_to papers_url }
      format.json { head :no_content }
    end
  end
end

Documents/UCSB_classes/papersphere-master/papersphere/app/helpers/papers_helper.rb
module PapersHelper
end

Documents/UCSB_classes/papersphere-master/papersphere/app/views/papers/_form.html.erb
<%= form_for(@paper) do |f| %>
  <% if @paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% @paper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :publication %><br />
    <%= f.text_field :publication %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Documents/UCSB_classes/papersphere-master/papersphere/app/views/papers/_paper.html.erb
<tr>
    <td>
        <%= form_tag({:controller => 'reading_list_papers', :action=> 'remove_paper_from_list'}, :remote => true, :method => :delete) do %>
            <%= hidden_field_tag :reading_list_id, @reading_list.id %>
            <%= hidden_field_tag :paper_id, paper.id %>
            <%= submit_tag 'Remove', :disable_with => 'Please wait...', :class => 'btn btn-danger btn-sm', :disabled => !(@is_owner or @has_modify_rights), :data => { :confirm => 'Are you sure?' } %>
        <% end %>
    </td>
    
    <td><%= link_to paper.title, @reading_list.reading_list_papers.select { |rlp| rlp.paper_id == paper.id }.first %></td>
    <td><%= paper.author %></td>
    <td><%= paper.year %></td>
    <td><%= paper.publication %></td>
    <td><%= link_to 'Source URL', paper.url %></td>
</tr>

Documents/UCSB_classes/papersphere-master/papersphere/app/views/papers/edit.html.erb
<h1>Editing paper</h1>

<%= render 'form' %>

<%= link_to 'Show', @paper %> |
<%= link_to 'Back', papers_path %>

Documents/UCSB_classes/papersphere-master/papersphere/app/views/papers/index.html.erb
<h1>Listing papers</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Year</th>
    <th>Publication</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @papers.each do |paper| %>
  <tr>
    <td><%= link_to paper.title , paper %></td>
    <td><%= paper.author %></td>
    <td><%= paper.year %></td>
    <td><%= paper.publication %></td>
    <td><%= paper.url %></td>
    <td><%= link_to 'Show', paper %></td>
    <td><%= link_to 'Edit', edit_paper_path(paper) %></td>
    <td><%= link_to 'Destroy', paper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Paper', new_paper_path %>

Documents/UCSB_classes/papersphere-master/papersphere/app/views/papers/new.html.erb
<h1>New paper</h1>

<%= render 'form' %>

<%= link_to 'Back', papers_path %>

Documents/UCSB_classes/papersphere-master/papersphere/app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @paper.title %>
</p>

<p>
  <b>Author:</b>
  <%= @paper.author %>
</p>

<p>
  <b>Year:</b>
  <%= @paper.year %>
</p>

<p>
  <b>Publication:</b>
  <%= @paper.publication %>
</p>

<p>
  <b>Url:</b>
  <%= @paper.url %>
</p>


<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>